### ISSUE TITLE
Data Inspection and Cleaning

### ISSUE THREAD

**Issue by aksurcos** [aksurcos/P5-Heritage-Housing#2]
As a Data Analyst, 
I want to identify missing values in all columns, so that I can take suitable action. 
I want to create statistical summaries so that I can see the abnormal values in the data.

Acceptance Criteria

1.  All columns are checked for missing data and missing values are handled.
2.  The dataset is cleaned from errors in data types and corrected.

Task
- [ ]  Identify columns with missing values.
- [ ]  Handle with missing values.
- [ ]  Implement strategies such as imputation or removal.
